export const Country=["nepal",
"Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Austrian Empire",
"Azerbaijan",

"Baden",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Bavaria",
"Belarus",
"Belgium",
"Belize",
"Benin ",
"Bolivia",
"Bosnia and Herzegovina",
"Botswana",
"Brazil",
"Brunei",
"Brunswick and Lüneburg",
"Bulgaria",
"Burkina Faso (Upper Volta)",
"Burma",
"Burundi",

"Cabo Verde",
"Cambodia",
"Cameroon",
"Canada",
"Cayman Islands",,
"Central African Republic",
"Central American Federation",
"Chad",
"Chile",
"China",
"Colombia",
"Comoros",
"Congo Free State",
"Costa Rica",
"Coted Ivoire (Ivory Coast)",
"Croatia",
"Cuba",
"Cyprus",
"Czechia",
"Czechoslovakia",


"Democratic Republic of the Congo",
"Denmark",
"Dominica",
"Dominican Republic",
"Duchy of Parma, ",



" Germany (German Democratic Republic)",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Eswatini",
"Ethiopia",



"Federal Government of Germany ",
"Fiji",
"Finland",
"France",


"Gabon",
"Gambia, The",
"Georgia",
"Germany",
"Ghana",
"Grand Duchy of Tuscany, The",
"Greece",
"Grenada",
"Guatemala",
"Guinea",
"Guinea-Bissau",
"Guyana",


"Haiti",
"Hanover",
"Hanseatic Republics",
"Hawaii", 
"Hesse",
"Holy See",
"Honduras",
"Hungary",


"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Israel",
"Italy",


"Jamaica",
"Japan",
"Jordan",

"Kazakhstan",
"Kenya",
"Kingdom of Serbia/Yugoslavia*",
"Kiribati",
"Korea",
"Kosovo",
"Kuwait",
"Kyrgyzstan",

"Laos",
"Luxembourg",
"Latvia",
"Lebanon",
"Lesotho",
"Lew Chew(Loochoo)",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
         "Luxembourg",
          "Zambia",
        "Zimbabwe",                                                                                     
        "Nassau",
        "Nauru",
        "Nepal",
        "Netherlands, The",
        "New Zealand",
        "Nicaragua",
        "Niger",
       " Nigeria",
       " North German Confederation*",
       " North German Union*",
       " North Macedonia",
       " Norway",
       "Namibia",
       " Oldenburg",
       " Oman",
      "  Orange Free State*",
    
       " Pakistan",
       " Palau",
        "Panama",
       " Papal States*",
        "Papua New Guinea",
        "Paraguay",
       " Peru",
        "Philippines",
       " Piedmont-Sardinia*",
        "Poland",
       
        "Republic of Genoa",
        "Republic of Korea (South Korea)",
       " Republic of the Congo",
        "Romania",
       " Russia",
       " Rwanda",
       
       " Saint Kitts and Nevis",
       " Saint Lucia",
        "Saint Vincent and the Grenadines",
       "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Schaumburg-Lippe*",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
       " Solomon Islands, The",
        "Somalia",
       " South Africa",
       " South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
       "Suriname",
        "Sweden",
        "Switzerland",
       " Syria",
        
        "Tajikistan",
        "Tanzania",
        "Texas",
       " Thailand",
       " Timor-Leste",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
       " Turkey",
       " Turkmenistan",
       " Tuvalu",
      " Two Sicilies*",
        
       " Uganda",
       " Ukraine",
       " Uruguay",
       " Uzbekistan",
        
        "Vanuatu",
       " Venezuela",
       "Vietnam",
        "W",
       " Württemberg*",
       
       " Yemen  ",                                                 

];                                